### PR TITLE
Update BMI and use bmipy package

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request updates the *BMI* for *RAFEM* to use the new *bmipy* package and the latest *BMI* spec.

### CODE REVIEW

**Comment by katmratliff** [comment]
Thank you @mcflugen! This was a lot of work.

**Comment by katmratliff** [comment]
Hey @mcflugen do you have an example script or input.yaml file for running rafem (or better yet running rafem coupled to CEM)?

**Comment by mcflugen** [comment]
@katmratliff An example *RAFEM* input file is in the input-files folder as [`default.yaml`](https://github.com/mcflugen/avulsion-bmi/blob/mcflugen/use-bmi-package/input-files/default.yaml).

An updated run script that couples *CEM*, *Waves*, and *RAFEM* is in the base folder my *rafem* repository as [`run_model.py`](https://github.com/mcflugen/avulsion-bmi/blob/mcflugen/use-bmi-package/run_model.py).

Until I create a conda package of *RAFEM*, it is a little awkward to install things, but not too bad. In the future (maybe tomorrow?) it will be as easy as `conda install pymt` but, until then, this is what I would do,
```bash
$ conda create -n rafem python
$ conda activate rafem
$ conda install pymt 
$ pip install rafem
```
This will install *pymt* and *RAFEM* into a new environment called *rafem* (we haven't installed *RAFEM* as a *pymt* component yet, we'll do that below). You can now run *RAFEM* on the default input file.
```bash
$ rafem default.yaml --days=7
```
This will run *RAFEM* for just 7 days - I imagine you would want to run it for a lot longer. You can use `rafem --help` to get a help message on using the *rafem* command (maybe `rafem --years=100 default.yaml`?).

To install *RAFEM* as a *pymt* component, you need to clone the *pymt_rafem* repository and install it from source.
```bash
$ git clone https://github.com/pymt-lab/pymt_rafem
$ cd pymt_rafem
$ pip install -e . -r requirements.txt
```
Now you should be able to access *rafem* from *pymt* and thus run the coupled experiment. Assuming that all went ok, the following should do the trick,
```bash
$ python run_model.py
```
I've tested that this runs and does something but I haven't looked at any output or anything like that.

**Comment by katmratliff** [comment]
Thank you for the info @mcflugen! I am out of town until Sunday and only have a windows machine, but I will play around with this on Sunday or Monday and let you know what the output looks like.

**Comment by katmratliff** [comment]
@mcflugen seems like a few tweaks are necessary to make run_model.py run the coupled models (at least on my end). I assume that `from cmt.components import Cem, Rafem, Waves` needs to be updated, and possibly some other things. Following syntax from the PyMT documentation, I tried `from pymt.models import Cem`, but I get this error message:
```
(rafem) Katherines-MBP:rafem-test kmratliff$ from pymt.models import Cem
from: can't read /var/mail/pymt.models
```
Any thoughts?

**Comment by katmratliff** [comment]
Update for @mcflugen: I've got everything installed. Just need to go through the run_model.py coupling script to update BMI syntax (e.g., `from cmt.components import` needed to be changed to `from pymt.models import`, and looks like the setup/initialize stuff needs to be changed as well).

**Comment by mcflugen** [comment]
@katmratliff The version of `run_model.py` that was in the pull request should have been adjusted for the new *pymt* syntax. However, it looks like you still have the old version of that file. The new version is still on my [fork](https://github.com/mcflugen/avulsion-bmi/tree/mcflugen/use-bmi-package).

I believe you no longer need to install from source. You should be able to install everything with,
```bash
$ conda create -n rafem pymt pymt_rafem -c conda-forge
$ conda activate rafem
```
I need to double check that though.

**Comment by katmratliff** [comment]
@mcflugen looks like I had merged in your PR before you updated `run_model.py`. I just pulled in the new changes and will test installation tonight. Thank you!!

**Comment by katmratliff** [comment]
@mcflugen Everything works with your initial set of installation instructions and your new `run_model.py` -- hooray! When I try to run the installation as follows,
```
$ conda create -n rafem pymt pymt_rafem -c conda-forge
$ conda activate rafem
```
I get this error message: 
```ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::affine-2.2.2-py_0'.
FileNotFoundError(2, "No such file or directory: '/Users/kmratliff/anaconda3/envs/rafem/bin/python3.7'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/Users/kmratliff/anaconda3/envs/rafem/bin/python3.7'")
```
So, not sure if it's helpful, but I was able to install and subsequently run the coupled model successfully this way:
```
$ conda create -n rafem python
$ conda activate rafem
$ conda install pymt 
$ conda install pymt_rafem
```

**Pull request merged**
